var rule = {
  title: '凌云影视',
  host: 'https://www.lyys8.com',
  url: '/channel/fyclass-fypage.html',
  searchUrl: '/sou.html?wd=**',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  class_parse: '.menu_bottom ul li;a&&Text;a&&href;.*/(.*?).html',
  cate_exclude: '解析|动态',
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.indexShowBox;ul&&li;a&&title;img&&data-src;.s1&&Text;a&&href',
  double: true,
  一级: '.pic-list&&li;a&&title;img&&data-src;.s1&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.content-rt&&p:eq(0)&&Text',
    img: '.img&&img&&data-src',
    desc: '.content-rt&&p:eq(1)&&Text;.content-rt&&p:eq(2)&&Text;.content-rt&&p:eq(3)&&Text;.content-rt&&p:eq(4)&&Text;.content-rt&&p:eq(5)&&Text',
    content: '.zkjj_a&&Text',
    tabs: '.py-tabs&&option',
    lists: '.player:eq(#id) li',
  },
  搜索: '.sr_lists&&ul&&li;h3&&Text;img&&data-src;.int&&p:eq(0)&&Text;a&&href',
}